package main

import (
	"fmt"
	"log"

	goaes "github.com/syronz/goAES"
)

func main() {
	// default length for terms is 100, if the origin text is more than 100 then you should
	// extend the length with .Lenght(int) chain.
	aes, err := goaes.New().Key("secret key").IV("iv is 16 char!!!").Length(10000).Build()
	if err != nil {
		log.Fatal(err)
	}

	term := `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium aenean pharetra magna ac placerat. Lobortis mattis aliquam faucibus purus in massa tempor nec. Urna porttitor rhoncus dolor purus non enim praesent elementum. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Enim eu turpis egestas pretium aenean pharetra magna ac. Eget nunc lobortis mattis aliquam faucibus purus in. Tristique nulla aliquet enim tortor at auctor urna. At risus viverra adipiscing at in tellus integer feugiat. Tincidunt arcu non sodales neque sodales ut. Elementum facilisis leo vel fringilla est ullamcorper. Rutrum quisque non tellus orci ac auctor. Netus et malesuada fames ac turpis egestas integer eget. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo. Nunc consequat interdum varius sit amet mattis vulputate enim nulla. Faucibus vitae aliquet nec ullamcorper sit. Est ultricies integer quis auctor elit sed vulputate mi. Posuere ac ut consequat semper viverra nam libero justo laoreet.
Dui ut ornare lectus sit amet. Turpis tincidunt id aliquet risus feugiat in ante. Euismod quis viverra nibh cras pulvinar mattis. Urna nec tincidunt praesent semper feugiat. Ut etiam sit amet nisl. Vestibulum morbi blandit cursus risus at ultrices mi. Vel pharetra vel turpis nunc eget lorem. Tempor nec feugiat nisl pretium fusce id velit. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Urna duis convallis convallis tellus id interdum velit. Scelerisque in dictum non consectetur a erat. Arcu dictum varius duis at. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Sit amet facilisis magna etiam.
Porttitor massa id neque aliquam vestibulum morbi. Nibh praesent tristique magna sit amet purus gravida. Faucibus a pellentesque sit amet porttitor eget dolor morbi non. Ipsum faucibus vitae aliquet nec ullamcorper sit. Nulla porttitor massa id neque aliquam vestibulum morbi. Diam vel quam elementum pulvinar etiam non. Sem fringilla ut morbi tincidunt augue interdum velit euismod in. Vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra. Nunc vel risus commodo viverra maecenas accumsan. Consectetur adipiscing elit pellentesque habitant morbi tristique.
Id porta nibh venenatis cras. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra. Elit at imperdiet dui accumsan sit amet nulla. Elit duis tristique sollicitudin nibh sit amet commodo. Donec enim diam vulputate ut. Interdum velit laoreet id donec ultrices. Suspendisse ultrices gravida dictum fusce ut placerat orci. Dolor morbi non arcu risus. Tellus mauris a diam maecenas. Sollicitudin aliquam ultrices sagittis orci a. Ut sem nulla pharetra diam sit. Risus quis varius quam quisque.
Amet volutpat consequat mauris nunc. In aliquam sem fringilla ut morbi tincidunt augue interdum. Adipiscing at in tellus integer feugiat scelerisque varius. Purus viverra accumsan in nisl nisi scelerisque eu. Justo laoreet sit amet cursus sit amet dictum sit. Diam phasellus vestibulum lorem sed. Mattis pellentesque id nibh tortor id aliquet lectus proin nibh. Posuere ac ut consequat semper. Sed vulputate mi sit amet mauris commodo quis imperdiet massa. Suspendisse sed nisi lacus sed. Id cursus metus aliquam eleifend mi in nulla. Cras ornare arcu dui vivamus arcu felis. Cursus vitae congue mauris rhoncus aenean vel. Fusce id velit ut tortor pretium viverra suspendisse. Sit amet tellus cras adipiscing. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus.
Blandit turpis cursus in hac habitasse. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Sem viverra aliquet eget sit amet tellus cras adipiscing. Aliquam sem et tortor consequat id porta nibh venenatis. Odio ut sem nulla pharetra diam sit amet nisl. Vulputate dignissim suspendisse in est ante in. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Hac habitasse platea dictumst quisque sagittis. Pharetra magna ac placerat vestibulum lectus. Integer malesuada nunc vel risus commodo. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Leo vel orci porta non pulvinar neque laoreet. Risus nullam eget felis eget nunc. Mi proin sed libero enim sed faucibus turpis. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Ultrices sagittis orci a scelerisque purus semper eget duis. Faucibus in ornare quam viverra orci sagittis eu. Eros donec ac odio tempor orci dapibus ultrices in. Nulla malesuada pellentesque elit eget gravida cum sociis.
Leo a diam sollicitudin tempor. Suscipit adipiscing bibendum est ultricies integer quis. Sit amet venenatis urna cursus eget. Consequat interdum varius sit amet mattis vulputate enim nulla aliquet. Tortor consequat id porta nibh venenatis cras sed felis. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Eget nunc lobortis mattis aliquam. Dolor purus non enim praesent. Blandit cursus risus at ultrices. Augue eget arcu dictum varius duis at. Faucibus scelerisque eleifend donec pretium vulputate. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.
Ante in nibh mauris cursus mattis molestie. Maecenas pharetra convallis posuere morbi. Rutrum tellus pellentesque eu tincidunt. Sit amet volutpat consequat mauris nunc congue. Mollis nunc sed id semper. Cras pulvinar mattis nunc sed. Imperdiet sed euismod nisi porta lorem mollis aliquam ut. Ut tortor pretium viverra suspendisse. Vel risus commodo viverra maecenas accumsan lacus. Pellentesque nec nam aliquam sem. Eget magna fermentum iaculis eu non diam. Purus gravida quis blandit turpis cursus in. Amet aliquam id diam maecenas ultricies mi eget mauris. Id cursus metus aliquam eleifend mi in nulla. Fusce id velit ut tortor pretium viverra suspendisse.
Neque vitae tempus quam pellentesque nec nam aliquam sem et. Ut venenatis tellus in metus vulputate. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Leo vel fringilla est ullamcorper. Lorem ipsum dolor sit amet consectetur. Dictum fusce ut placerat orci nulla pellentesque dignissim. Varius duis at consectetur lorem donec massa sapien faucibus. Dignissim enim sit amet venenatis urna cursus eget nunc scelerisque. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Volutpat est velit egestas dui. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Suscipit tellus mauris a diam maecenas sed. Cursus eget nunc scelerisque viverra mauris in aliquam.
Lacus sed viverra tellus in. Enim praesent elementum facilisis leo. Gravida arcu ac tortor dignissim convallis aenean et. Dui id ornare arcu odio ut. Tellus in hac habitasse platea dictumst. At volutpat diam ut venenatis tellus in metus. Tincidunt augue interdum velit euismod in. Scelerisque varius morbi enim nunc faucibus a. Pretium aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Pretium nibh ipsum consequat nisl vel pretium lectus quam. Vulputate eu scelerisque felis imperdiet proin fermentum leo. Vitae tortor condimentum lacinia quis vel eros donec ac. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Donec et odio pellentesque diam volutpat commodo sed egestas. Massa massa ultricies mi quis hendrerit dolor magna. Sed id semper risus in hendrerit. Habitant morbi tristique senectus et. Mattis aliquam faucibus purus in massa tempor nec feugiat nisl.`

	encrypted := aes.Encrypt(term)
	fmt.Printf("Encryption of 'Lorem...' is: \n %q \n", encrypted)

	decrypted := aes.Decrypt(encrypted)

	fmt.Printf("Decryption of '21779bdc59677aba2...' is: \n %q \n", decrypted)
}
